# This file contains all configurable parameters for downloading climate model data
# from the Earth System Grid Federation (ESGF)

# ESGF Node Configuration
esgf:
  myproxy_host: "esgf-node.ipsl.upmc.fr"
  #search_node: "http://esgf-data.dkrz.de/esg-search"       # Germany (dkrz)
  #search_node: "http://esgf-node.ipsl.upmc.fr/esg-search"  # France (ipsl)
  #search_node: "https://esgf.nci.org.au/esg-search"         # Australia (nci)
  #search_node: "https://esg-dn1.nsc.liu.se/esg-search"       # Sweden (nsc)
  search_node: "https://esgf-node.ornl.gov/esg-search"       # USA (llnl)

  data_node_preference: "esgf-node.ornl.gov" #"esgf.ceda.ac.uk"

# Download Configuration
download:
  max_workers: 8  # Number of parallel downloads (adjust based on network/server limits)

# Data Selection Configuration
data:
  project: "CMIP6"
  frequency: "mon"        # time resolution: 3hr, day, mon, yr
  
  scenarios:
    #- "historical"
    - "ssp126"
    - "ssp534-over"
    - "ssp585"
  
  # If true, only download 2300 extensions for ssp126, ssp585, ssp534-over.
  # Has no effect for any other experiment.
  2300_extensions: true
  
  # Variables follow ESGF naming conventions
  variables:
    - "tas"       # surface temperature
    - "pr"        # precipitation
    - "evspsbl"   # evaporation and sublimation
    - "mrro"      # runoff
    #- "thetao"    # ocean potential temperature
    #- "so"        # ocean salinity
  
  # Specific model versions required – see ESGF web search tool for details
  models:
    #- "CESM2-WACCM"  # done
    #- "IPSL-CM6A-LR" # done
    #- "MRI-ESM2-0" # done
    #- "ACCESS-ESM1-5" # done
    #- "ACCESS-CM2"
    #- "CanESM5" # done
    #- "EC-Earth3-Veg" # done
    - "MIROC-ES2L" # missing thetao, so
    #- "CNRM-ESM2-1" # missing ssp126, 585
    #- "UKESM1-0-LL" # done

# Variable to Table ID Mapping
# Amon - atmosphere, Omon - ocean, Lmon - land surface
# Any new variables added above should also be added here with the appropriate table ID
table_mapping:
  tas: "Amon"
  pr: "Amon"
  evspsbl: "Amon"
  mrro: "Lmon"
  thetao: "Omon"
  so: "Omon"

# Model Variant Labels
# Enter custom variant labels for models here
variant_labels:
  default: "r1i1p1f1"
  UKESM1-0-LL: "r4i1p1f2"
  MIROC-ES2L: "r1i1p1f2"
  #CNRM-ESM2-1: "r1i1p1f2" # only for ssp534-over
  #ACCESS-ESM1-5: "r1i1p1f2" # only for ssp534-over

# Variable Grid Labels  
# gn - native grid, gr - regridded to lat-lon
# Check ESGF search results if downloads fail - the variable may need a different grid label
grid_labels:
  default: "gn"
  # tas: "gr"
  # pr: "gr"
  # evspsbl: "gr"
  # mrro: "gr"